### ISSUE TITLE
Can visit chat topics directly if id is known

### ISSUE THREAD

**Issue by gdpelican** [gdpelican/babble#102]

**Comment by AamuLumi** [comment]
Get the same issue.
I create a channel only for staff group, and I can access to the corresponding topic if I get the link on a not-staff account.

Is there a way to avoid that ?

**Comment by gdpelican** [comment]
Lucky you; I was just working on this!
#119

**Comment by gdpelican** [comment]
Updating to the latest should take care of this nasty little problem :)

**Comment by AamuLumi** [comment]
Good job ! :) And thanks a lot for all !
