### ISSUE TITLE
Un-hard-code Babble User id

### ISSUE THREAD

**Issue by gdpelican** [gdpelican/babble#11]
Currently the id of the created Babble::User is hardcoded to -2, which is a little bit safe but not that safe. We should extract this to a hidden site setting, per the suggestion [here](https://meta.discourse.org/t/babble-a-chat-plugin/31753/21)

**Comment by JSey** [comment]
Anybody found an example of how to implement a hidden site setting?

**Comment by gdpelican** [comment]
Closed with #20
