### ISSUE TITLE
Automatic checking of language translations (locale files)

### ISSUE THREAD

**Issue by lassik** [gdpelican/babble#125]
Hi,

Here's a little script I wrote to automatically check for missing translations:

https://gist.github.com/lassik/cec99172f390f1f231b9

I don't know if it's appropriate to include in the Babble repo, or if Discourse already provides something fancier (I couldn't find any such tool), but I find this useful.

Regards,
Lassi

**Comment by gdpelican** [comment]
Cool, thanks! I think the best thing might be to put a link there in the README so folks can find it if they like.

**Comment by lassik** [comment]
Sounds like a good solution to me :)

**Comment by gdpelican** [comment]
I've moved Babble onto Transifex (http://transifex.com/babble/babble) which should serve the purpose of this nicely (Finnish is still at 100% at the moment :) )
