### ISSUE TITLE
Allow flagging / editing / deleting of posts

### ISSUE THREAD

**Issue by gdpelican** [gdpelican/babble#129]
To further expand the 'adminability' of the chats, it would be a nice improvement to expose the flag, edit, and delete functions for people with appropriate permissions in the chat UI.

**Comment by smacz42** [comment]
Indeed. I'm looking into this for a mod team and this would be a great ability to have. I'm not a UI guy by any means, but what did you have in mind?

**Comment by gdpelican** [comment]
Well, here's my totally-not-quite-working example so far:

http://g.recordit.co/bOU4RZ7aVh.gif

(You'll note I still have to page reload to get the updates to show up in the stream)
I reckon that pencil will turn into a dropdown of some kind which would let you pick from flag, edit, or delete.

Stay tuned! :heart:

**Comment by gdpelican** [comment]
I've just merged in editing and deleting post functionality, so I'm closing this and opening a separate issue for flagging.
