### ISSUE TITLE
Create offline page for widget testing/development

### ISSUE THREAD

**Issue by gtanczyk** [gdpelican/babble#13]
After few hours with this plugin I see huge bottleneck: Discourse environment. There should also some communication layer that would be substituted with an adapter for offline testing.

Something example: https://github.com/gamedevpl/gamedev-chat/tree/master/tests
- simple nodejs server
- adapter code substitutes production code

This will be extremely useful for working on UI/UX. It will also help with running tests for UI.

**Comment by gdpelican** [comment]
While I think this is a good idea, it's not something I'm going to invest time into, so unless someone else feels like they want to take ownership of this, I'm going to close for now.
