### ISSUE TITLE
Window display issue in latest Babble/Discourse

### ISSUE THREAD

**Issue by ashipde** [gdpelican/babble#131]
With the current Babble release installed on the current Discourse version, I see a window display issue with Safari 9, Firefox 44 and Chrome 48 (all on Mac OS X 10.11). In Firefox clicking the blow-horn Babble icon opens a tiny, may be 10px-tall empty window. In Safri and Chrome I get an empty window that is as tall as the browser windows.

**Comment by gdpelican** [comment]
Thanks. They've suddenly updated the plugin API in Discourse, which broke most of the existing third party plugins which render things on the frontend. It'll be a bit of work to get it working again.

More details here: https://meta.discourse.org/t/a-new-versioned-api-for-client-side-plugins/40051

**Comment by gdpelican** [comment]
Closing as dup of #130 . Hope to get to this soon!
