### ISSUE TITLE
Strip Chatty Kathy of her admin priviledges

### ISSUE THREAD

**Issue by gdpelican** [gdpelican/babble#133]
Right now Chatty Kathy's an admin, but I don't think she needs to be

**Comment by mikechristopher** [comment]
I can see the account details in the settings.yml but not where you request the account to be set up

Can the system account not be used in this instance as the account is only to create the initial post isnt it?  Surely with the system account being number -1 in each instance could that not be used?

**Comment by gdpelican** [comment]
The user is set up in Babble::User in plugin.rb, which is set up as a singleton.

https://github.com/gdpelican/babble/blob/master/plugin.rb#L237

Originally, we were tracking which topics were chat topics by saying `Babble::User.instance.topics` (all the topics CK created) I think we could/should instead say `Babble::Category.instance.topics` (all topics in the 'chat' category)

I can't recall off the top of my head why we needed admin privileges to create those topics, but I definitely did try using the system user first. It's likely a better idea to jigger the Guardian a bit to allow the system user to create chat topics though, rather than having this random floating admin around.

**Comment by gdpelican** [comment]
I totally nuked Chatty Kathy last week! Existing instances should be able to get rid of her safely now.
