### ISSUE TITLE
Going to Babble admin panel shows low-level error message when Babble is disabled

### ISSUE THREAD

**Issue by lassik** [gdpelican/babble#134]
When Babble is disabled, going to `yourforum.example.com/admin/chats` shows Discourse error page (a page with a big frowning smiley `:(` that says: error loading `/babble/topics.json`).

Visiting `yourforum.example.com/babble/topics.json` gives:

```
{
errors: [
"ApplicationController::PluginDisabled"
]
}
```

(We are using the forum in Finnish, for what it's worth.)

**Comment by gdpelican** [comment]
I've fixed this in the latest :+1:

**Comment by lassik** [comment]
Thanks :)
