### ISSUE TITLE
Don't remove unread message on open popup

### ISSUE THREAD

**Issue by MiguelAngelLV** [gdpelican/babble#135]
When I have unread message and click on popup, the unread message counter don't hide. It only hide when I write a new message.

**Comment by kymetro9999** [comment]
Same here. Caused my users to play leap frog, each one trying to clear out their notifications by posting.... which caused notifications to grow for all others. I've turned off the whole extension until this bug gets fixed.

**Comment by gdpelican** [comment]
Should be fixed in the latest :)
