### ISSUE TITLE
Don't override header.hbs, add plugin outlet to Discourse

### ISSUE THREAD

**Issue by gtanczyk** [gdpelican/babble#14]
Is this required: https://github.com/gdpelican/babble/blob/master/assets/javascripts/discourse/templates/header.hbs

Should we add plugin outlet to Discourse?

**Comment by gdpelican** [comment]
You'd need to add two outlets, one for the icon and one for the dropdown. I
imagine those could both go into Discourse, though.

**Comment by gtanczyk** [comment]
Is there any other way to do that from plugin?

**Comment by gdpelican** [comment]
Not that I know of. Maybe asking in the plugin thread would get Sam or Kane's head thoughts on it a little. https://meta.discourse.org/t/babble-a-chat-plugin/31753/26

**Comment by gtanczyk** [comment]
@gdpelican PR in Discourse was just merged

**Comment by gdpelican** [comment]
Sweet, I'll smoke test this tonight and hopefully get it merged in; thanks
a ton!

**Comment by gdpelican** [comment]
Closed with #15
