### ISSUE TITLE
Who's in the room

### ISSUE THREAD

**Issue by gdpelican** [gdpelican/babble#142]
Would be good to have some indicator of who's online at a given moment.

Would require a little design; could be info which lived in the 'eyeball' tooltip.

**Comment by rblagahit** [comment]
This will be very much ideal.

**Comment by RobinjLab** [comment]
I also got this request from my users as soon as I enabled babble. Would be great to have it.

**Comment by gdpelican** [comment]
Okay, I've got this up and going. Should be good to go soon.

![image](https://cloud.githubusercontent.com/assets/750477/25315684/313e4ab4-2894-11e7-8065-ad7813d83ed8.png)
