### ISSUE TITLE
Emoji picker div (partially) invisible

### ISSUE THREAD

**Issue by JSey** [gdpelican/babble#147]
As described [here](https://meta.discourse.org/t/babble-a-chat-plugin/31753/274?u=jsey), the smiley picker div becomes invisible when launched too far on the right. Example below.
![bildschirmfoto 2016-03-20 um 19 59 50](https://cloud.githubusercontent.com/assets/9109505/13906463/e489e1b2-eed6-11e5-96bf-adcfa57a4991.png)

Changing the text-align back to “left” does not really help (well, ok, in about 80% of the cases, yes, since you can see and click the emojis - consider this the ugliest hack for the problem presented here…): 
![bildschirmfoto 2016-03-20 um 20 04 58](https://cloud.githubusercontent.com/assets/9109505/13906475/0d503056-eed7-11e5-9b7e-6e8563986e13.png)

**Comment by gdpelican** [comment]
I totally fixed this! #148

**Comment by JSey** [comment]
Great, thx!
