### ISSUE TITLE
Emoji selector modal dialog minor UI glitch

### ISSUE THREAD

**Issue by JSey** [gdpelican/babble#150]
**Expected behavior**:

1. open emoji dialog with the button
1. dismiss the dialog without selecting an emoji by clicking outside the modal dialog
1. clicking beside the babble window should dismiss the babble dialog as usual.

**Actual behavior**:
number 3. does not happen. Pressing Esc or the Babble icon does, however. 

Another minor thing: in the emoji dialog, pressing Esc dismisses both Babble and the emoji dialog.

**Comment by gdpelican** [comment]
I think #154 should make this a better overall experience.
