### ISSUE TITLE
Have the chatbox stay open when switching page

### ISSUE THREAD

**Issue by smacz42** [gdpelican/babble#152]
Similar to how the 'compose message' dialog stays open when switching to a new page, having the chatbox stay open when switching to a new page (not tab, but page - like following a link in the same tab) would align more with the original idea of how discourse functioned. Sort of like a HUD in a way.

**Comment by gdpelican** [comment]
Ooh, good call. Actually pretty much my favorite part about the composer is that it sticks around through navigate, which lets you do a little research while you're composing.

Would love a PR for this :smiley_cat:

**Comment by gdpelican** [comment]
We actually support this in the new sidebar branch (one of the best parts about the new sidebar branch)
