### ISSUE TITLE
Timestamps broken

### ISSUE THREAD

**Issue by JSey** [gdpelican/babble#162]
The new edit+delete functionality (which I love) has somehow broken the timestamping. After an edit, all new posts get the timestamp from the edited post. Safari really pukes on the post and marks that as “invalid”, and in Chrome you get this:
![bildschirmfoto 2016-04-09 um 20 02 36](https://cloud.githubusercontent.com/assets/9109505/14405386/5f6fa9c2-fe8e-11e5-9da4-db22d18eb1be.png)
Before the reload, everything I wrote was stamped “2h”, the reload fixed the existing posts, and the next new post was again at “2h”… odd.

**Comment by gdpelican** [comment]
There's some sort of timezone business going on where it's updating UTC times instead of local times, some of the time. I'll have a look.

**Comment by gdpelican** [comment]
I fixed it! #163
