### ISSUE TITLE
demo does not work

### ISSUE THREAD

**Issue by pszi1ard** [gdpelican/babble#168]
"Sorry, we couldn't load that topic, possibly due to a connection problem. Please try again. If the problem persists, let us know."

**Comment by gdpelican** [comment]
Er, I don't seem to be having that problem. Is it still not working? Can you provide some reproduction steps? Is it possible you had a connection problem?

**Comment by pszi1ard** [comment]
Sorry, I did not realize that I have to be logged in order to open some of the threads, that error message does not seem to indicate this. Actually, the "Great Job! - Fifteen Character Limit" topic disappears when I log in.

I've some questions about the intended chat functionality, but I should ask on the demo site, I guess.

Thanks for the quick feedback!
