### ISSUE TITLE
Plug in Babble into Discourse notifications

### ISSUE THREAD

**Issue by gtanczyk** [gdpelican/babble#17]
It does not seem to work out of the box, anyways it should trigger notifications on its own. Make it configurable.

**Comment by gdpelican** [comment]
Hey @gtanczyk could you expand a little on what you're thinking here? That getting a new chat message should trigger a notification where? I assume we don't want notifications triggered in the navbar, right?

**Comment by gtanczyk** [comment]
There is desktop notifications library in Discourse: https://github.com/discourse/discourse/blob/master/app/assets/javascripts/discourse/lib/desktop-notifications.js.es6

I did a quick spike and it is quite easy to use. I used it in ```Discourse.Babble.refresh```.

So this issue is about displaying desktop notifications.

**Comment by gdpelican** [comment]
:+1:

On Wed, Aug 12, 2015 at 12:08 PM, Grzegorz Tańczyk <notifications@github.com

**Comment by gdpelican** [comment]
I'm going to close this as a feature request; it's not on the roadmap at this time.
