### ISSUE TITLE
"... is typing" message makes too many requests to backend

### ISSUE THREAD

**Issue by SystemZ** [gdpelican/babble#183]
Currently on beta branch each keystroke generates 1 POST to backend.
This results in DoS for forum when typing message.

![screenshot at 12-35-34](https://cloud.githubusercontent.com/assets/1836094/16836789/b1c90e26-49bf-11e6-98c5-728636cabeeb.png)

Chart for average CPU is much higher after upgrading plugin with this notification.
Typing results 100% CPU on server for a couple of seconds or minutes if there are more people typing.

![screenshot at 12-39-44](https://cloud.githubusercontent.com/assets/1836094/16836834/10aa8140-49c0-11e6-88cc-4ad5b51dc2d8.png)

Maybe better idea will be mechanism like in Discourse search box?

**Comment by gdpelican** [comment]
Thanks for the report. @xfix can you add a reasonable debounce to this call? There's a handy function in `discourse/lib/debounce` that should fix this.

**Comment by gdpelican** [comment]
I've merged this into the beta branch and will deploy to discourse-babble.com. If that stands up over the next day or two, I'll merge into the master branch. Thanks for the report @SystemZ !

**Comment by SystemZ** [comment]
I tested it and now it's fixed. Many thanks :)
