### ISSUE TITLE
Display username in chat?

### ISSUE THREAD

**Issue by companyhen** [gdpelican/babble#191]
My chat has a lot of users and I know you can hover over the avatar to view the name, but is there a way to display the username in the chat as well? Maybe in place or beside the avatar?

**Comment by gdpelican** [comment]
This has been suggested in the Babble thread (https://meta.discourse.org/t/babble-a-chat-plugin/31753/400) and is a thing I may make possible with some custom css soon.

**Comment by companyhen** [comment]
Cool. Also you could just hyperlink the avatar so when it's clicked it inserts @username in the chat box (suggested by a user)

**Comment by RobinjLab** [comment]
Even though you can hover over it to see the username on desktop, there's no way to tell who you're speaking to if using Babble on mobile other than long pressing the avatar which prompts an image download with a title of the username.
