### ISSUE TITLE
Wrong emoji suggestion

### ISSUE THREAD

**Issue by SystemZ** [gdpelican/babble#192]
When I type `:D` there is a dagger
![screenshot at 18-55-21](https://cloud.githubusercontent.com/assets/1836094/17221630/e3ef6e46-54f4-11e6-9613-9c8eb2b01fbf.png)

 instead of smile

![screenshot at 18-56-43](https://cloud.githubusercontent.com/assets/1836094/17221675/0b4b34fc-54f5-11e6-86d7-2d64e1098e15.png)

**Comment by gdpelican** [comment]
Thanks for the report; I think we're lower casing the input for suggestions when maybe we don't need to.

**Comment by gdpelican** [comment]
I finally took out the lowercasing thing here 👍
