### ISSUE TITLE
Emoji pagination destroy message and hides shoutbox

### ISSUE THREAD

**Issue by SystemZ** [gdpelican/babble#193]
Steps to reproduce:
1. Type message in shoutbox
2. Click emoji icon to show modal with emoji
3. Click arrow to select another page of emoji

**Comment by gdpelican** [comment]
Yep, can confirm this.

**Comment by gdpelican** [comment]
Welp, the emoji picker has completely changed since this was a bug, so this isn't a bug anymore, yay!
