### ISSUE TITLE
Mobile use

### ISSUE THREAD

**Issue by CrystaletResearch** [gdpelican/babble#199]
When I open the chat screen on my phone the border with the browser functionality in safari blocks the actual chat entry. If I flip my screen I can get a little bit of the entry box but then i can barely see the chat posts (only last one is visble)

Even when typing, the experience is a bit strange as my screen keeps flashing...

**Comment by r76941156** [comment]
Me too.

**Comment by Sylvain-Kraisin** [comment]
It seems that the problem come from Safari because it s not working properly on desktop with Safari too.

**Comment by Sylvain-Kraisin** [comment]
<img width="563" alt="capture d ecran 2016-11-26 a 20 07 57" src="https://cloud.githubusercontent.com/assets/14780460/20642632/0f8b30a2-b414-11e6-86b9-c32cf490097b.png">

**Comment by lukasreussner** [comment]
@gdpelican I totally agree with @CrystaletResearch. The chat definitely needs some improvement regarding the mobile usability. Here is a quick look at the experience I'm having on my cell phone. It's even not possible to reach the entry box to type in a message.
![2017-01-11 14_48_22](https://cloud.githubusercontent.com/assets/19549140/21851130/0372ff02-d80e-11e6-8d64-868bc2a8d5e5.gif)

**Comment by jorgtron** [comment]
Adding my vote to this :)

**Comment by babyfooter** [comment]
Same issues on Safari here too, both on OSx and iOS versions :-)

**Comment by gdpelican** [comment]
Hm, this is very odd behaviour; I don't personally own an iDevice of any kind, but I'll borrow one in the next wee while to see if I can't figure out why it's doing this.

**Comment by jorgtron** [comment]
I haven't checked, but I assume you might be able to troubleshoot using the iOS simulator in Xcode.

**Comment by gdpelican** [comment]
I've gotten a device to test on and am going to have a swing this weekend. :D

**Comment by jorgtron** [comment]
Awesome! Thanks again for developing the plugin, it's turning into a killer feature on my forum :)

**Comment by gdpelican** [comment]
Alright, I've made some progress here and pushed it up to the beta branch. (NB: this will require running the latest version of Discourse)

Not going to close it quite yet as safari still has some weirdo behaviour here while typing. Will continue hacking at it this week.

**Comment by curioussavage** [comment]
woops, I totally missed this issue before I submitted https://github.com/gdpelican/babble/pull/217

**Comment by curioussavage** [comment]
yikes. can't type at all now. confused because all I changed was css.

`event.key` is undefined here - https://github.com/gdpelican/babble/blob/22efe3148b3de311a956204e117fe49d096c6cce/assets/javascripts/discourse/widgets/babble-composer.js.es6#L102

**Comment by gdpelican** [comment]
I've put in a hotfix for the `event.key` erroring; it seems that particular feature isn't quite cross browser just yet (it's checking to see if you've typed a character [and are thus 'typing'], or if you typed something else like a tab or alt or esc [in which case we should ignore that keystroke]).

What browser are you using while seeing the error?

**Comment by curioussavage** [comment]
IOS safari

**Comment by gdpelican** [comment]
Closing as I haven't heard reports of this in a long time, still very keen to hear about any mobile bugs that people are experiencing though.
