### ISSUE TITLE
Notification badge on bullhorn icon not appearing

### ISSUE THREAD

**Issue by JSey** [gdpelican/babble#2]
**Expected behavior**: when someone posts a chat message, it should either instantly show in the chat message list (which is working) or it should display a badge on the bullhorn icon like so:
![bildschirmfoto 2015-08-04 um 18 49 14](https://cloud.githubusercontent.com/assets/9109505/9066734/8c4fcb12-3ad9-11e5-8a80-5034cce10192.png)

**Actual behavior**: the chat message list updates all right, but if it's closed, the notification badge only displays if you reload the site.

**Comment by JSey** [comment]
This fixes it: https://github.com/gitter-badger/babble/commit/ffd57130465286cde8fc15152388420bc6a8a7b7

**Comment by gdpelican** [comment]
Cool. Yep, the flashing 1 icon is on my list of things to fix, probably detecting if the post that's coming in is written by the current user or something.

Closing this for now though; I'll open up a separate issue for the flashing 1.

**Comment by JSey** [comment]
Not working reliably. It does between two browsers on my computer. But not between a staff member of my team and me.
