### ISSUE TITLE
Add new steps in readme for installation

### ISSUE THREAD

**Issue by bdombro** [gdpelican/babble#202]
Please add steps to set the settings page and create a chat room.  I installed the plugin and had to figure out on my own that I needed to configure the plugin on the plugin settings page, AND that I had to create a chat room before the chat would work.

**Comment by gdpelican** [comment]
Hm, I had this written in the readme; what steps were missing for you?

![screen shot 2016-10-19 at 10 56 53 am](https://cloud.githubusercontent.com/assets/750477/19524180/dcd7f060-95ea-11e6-929c-69c29295e893.png)

**Comment by bdombro** [comment]
Oh, my mistake!

On Wed, Oct 19, 2016 at 10:57 AM, James Kiesel <notifications@github.com> wrote:
Hm, I had this written in the readme; what steps were missing for you?

[https://cloud.githubusercontent.com/assets/750477/19524180/dcd7f060-95ea-11e6-929c-69c29295e893.png]

**Comment by gdpelican** [comment]
No worries, thanks for using it!
