### ISSUE TITLE
Sidekiq Errors

### ISSUE THREAD

**Issue by fearlessfrog** [gdpelican/babble#203]
Running Discourse v1.7.0.beta6 and latest on main branch of Babble as of today.

Getting Sidekiq errors as follow:

Jobs::HandledExceptionWrapper: Wrapped NoMethodError: undefined method `admin' for nil:NilClass
	
{"post_id"=>29877, "bypass_bump"=>false, "invalidate_oneboxes"=>true, "cooking_options"=>nil, "current_site_id"=>"default"}

Jobs::ProcessPost

We have many log errors as follow, which seems to indicate it is related to babble:

/var/www/discourse/plugins/babble/plugin.rb:379:in `available_topics_for'
/var/www/discourse/plugins/babble/plugin.rb:442:in `can_see_topic?'
/var/www/discourse/lib/guardian/post_guardian.rb:158:in `can_see_post?'
/var/www/discourse/lib/guardian.rb:90:in `can_see?'
/var/www/discourse/lib/cooked_post_processor.rb:53:in `grant_badges'
/var/www/discourse/lib/cooked_post_processor.rb:37:in `block in post_process'
/var/www/discourse/lib/distributed_mutex.rb:21:in `synchronize'
/var/www/discourse/lib/distributed_mutex.rb:5:in `synchronize'
/var/www/discourse/lib/cooked_post_processor.rb:31:in `post_process'
/var/www/discourse/app/jobs/regular/process_post.rb:24:in `execute'
/var/www/discourse/app/jobs/base.rb:154:in `block (2 levels) in perform'

The plugin is very popular with our community, so is it best to perhaps move to a different branch or wait for the full-page stuff? Thanks for any help.

**Comment by gdpelican** [comment]
Hm, I believe I just fixed this in the latest Babble. Care to give it a go? 🐸

**Comment by fearlessfrog** [comment]
Thanks for such a quick response (and Babble in general 😃 )

We're just waiting for https://meta.discourse.org/t/add-a-custom-picture-option-has-disappeared/51795/2 to be fixed (hopefully very soon) and will update to test that out.

How close is the full-page-chat being to beta'ing on a live site? We're curious to try that and happy to help with any testing.

**Comment by fearlessfrog** [comment]
Yep, that fixed it. Thanks!

**Comment by gdpelican** [comment]
@fearlessfrog Will definitely announce when we have this thing live. It's chugging along. :)
