### ISSUE TITLE
Full page chat bug

### ISSUE THREAD

**Issue by companyhen** [gdpelican/babble#207]
Trying to create a new chat channel and get this message no matter what the channel title is or who it is visible to. Any ideas? Really want to test out Full Page Chat! Thanks.

I am use the beta branch and am latest version: Discourse 1.7.0.beta7		

<img width="685" alt="screen shot 2016-11-09 at 10 04 26 pm" src="https://cloud.githubusercontent.com/assets/1679107/20163213/b45922b4-a6c8-11e6-9f23-3c8d6d9fdd56.png">

**Comment by angusmcleod** [comment]
This is resolved.
