### ISSUE TITLE
Bug with category based permissions when 'Full page chat' option is enabled

### ISSUE THREAD

**Issue by rysherz** [gdpelican/babble#210]
There seems to be a bug with permissions when 'Full page chat' option is enabled.

The steps to reproduce: 
1) git clone -b beta https://github.com/gdpelican/babble.git
2) Create a category 'CategoryName' and group 'GroupName'
3) Give full permissions for 'CategoryName' to 'GroupName'
4) enable 'Full page chat' option and create a new Chat Channel with Category Permission and associate the channel with 'CategoryName' category.
5) login as a user from 'GroupName' and go to 'CategoryName' Chat tab 
ATTENTION! This user shouldn't be in Admin group.

Result: endless 'Loading' icon.

In the connections you will see: 
Request URL: https://example/chat/categoryname/136.json?_=1481033081154
Request Method:GET
Status Code:403 
{"errors":"You are unable to view this chat topic"}

At the same time, this user can see topics in this category.

**Comment by gdpelican** [comment]
We've since removed the full page chat option, so this is no longer a bug. :)
