### ISSUE TITLE
Every chat message is posted twice

### ISSUE THREAD

**Issue by rysherz** [gdpelican/babble#211]
The steps to reproduce:
1) git clone -b beta https://github.com/gdpelican/babble.git
2) create a chat room
3) post any message in the chat
Result: every message is posted twice.

![double-post-issue](https://cloud.githubusercontent.com/assets/24416770/21223934/cb1d0a50-c2da-11e6-952b-ea26fa3dba70.png)

**Comment by StefanBrand** [comment]
Please post some more details about your setup.

I'm on Firefox 50.1.0 / Windows 10 and don't have duplicate posts.

**Comment by rysherz** [comment]
I already removed the installation after this time. But there were several other users on https://meta.discourse.org/t/babble-a-chat-plugin/31753/498 that also had this issue.

It was a default setup with the full-page chat enabled option.

**Comment by StefanBrand** [comment]
A friend was using Firefox on Mac OS X and also had duplicate messages. (We were both trying out the demo at http://discourse-babble.com/ )

**Comment by gdpelican** [comment]
This should be fixed in the latest. Thanks for the report!
