### ISSUE TITLE
Have chatbox fill right side of the screen

### ISSUE THREAD

**Issue by p12y** [gdpelican/babble#220]
I think it would be nice if the chatbox took up more space on the page. (Say ~40% of the entire page.) Then there could be links at the top to open it in a pop-up window or close the chatbox. I've enclosed a picture of something similar. What do you think?

![screenshot from 2017-03-06 00 38 19](https://cloud.githubusercontent.com/assets/14144032/23597996/64292814-0205-11e7-8a74-768d0111e656.png)

**Comment by gdpelican** [comment]
Have you tried achieving this with some custom css? Putting in

```
.babble-menu .menu-panel.slide-in {
  width: 500px !important;
}
```

might be an interesting place to start.

I do have it on my list to put links to the full page chat up there on the
top right of the chat panel.

**Comment by ptylde** [comment]
I've had a little play around with it, but I think there will be a bit more to it than that. The chat box is within a 'wrap' div which is keeping it in line with the rest of the page's content. I'll fork the repo and see what I can come up with. Thanks for making this great plugin!

**Comment by jorgtron** [comment]
> .babble-menu .menu-panel.slide-in {
>  width: 500px !important;
> }

This does not seem to work, one of the divs has an inline style with "width: 300px" which cannot be overridden this way - I haven't quite been able to change this yet.

@ptylde: you might find this interesting, too: https://meta.discourse.org/t/babble-a-chat-plugin/31753/554?u=discoursemetrics.com

:)

**Comment by gdpelican** [comment]
We're actually moving in this direction with the sidebar branch, which will be ready to go soon. Stay tuned.

**Comment by jorgtron** [comment]
Looking forward to it @gdpelican :)

**Comment by gdpelican** [comment]
This is now an option under the Babble site settings
