### ISSUE TITLE
Bullhorn widget gone after upgrade

### ISSUE THREAD

**Issue by SystemZ** [gdpelican/babble#222]
Hello, after standard Dockerized Discourse install upgrade on 9 March babble icon on right side just disappeared. Full screen page chat works ok.
I tried to on/off plugin or add new chat room but with no effect.

On Chrome JS console I see something like this, not sure if related:
![screenshot from 2017-03-30 21-25-04](https://cloud.githubusercontent.com/assets/1836094/24522285/61e09784-158f-11e7-991f-2f255948dcc3.png)

My plugins:
![screenshot from 2017-03-30 21-29-01](https://cloud.githubusercontent.com/assets/1836094/24522451/eb286134-158f-11e7-8c88-12326531af48.png)

One simple custom plugin "Hide PM" source:
https://github.com/kacpersaw/discourse-hide-pm

How can I debug this more deep?

**Comment by Sylvain-Kraisin** [comment]
Same problem since today update with last commit. The chat icon disappeared.

**Comment by SystemZ** [comment]
@Sylvain-Kraisin I wonder if it's plugin related. Can you post your plugins list?

**Comment by SystemZ** [comment]
Ok, so d3e520f9232ec35cfb99bd1931d7d75562264c34 fixed this for me :)

How about you @Sylvain-Kraisin , can I close this issue?

**Comment by gdpelican** [comment]
This looked to be the conflict with discourse-voting, which is now resolved. Thanks for the report!
