### ISSUE TITLE
Babble breaks Discourse on Win10 + IE11

### ISSUE THREAD

**Issue by jorgtron** [gdpelican/babble#223]
Several users have reported that they can no longer access topics on the forum when Babble is enabled. They see blank pages / endless loading spinners. All were using Windows 10 and IE11.

**Comment by gdpelican** [comment]
Hrm, I haven't been able to repro this (although I don't have access to an IE machine at the moment)

Any error messages in the logs that you or your users can see?

**Comment by gdpelican** [comment]
I just had a play with the new sidebar branch and deemed it 'good enough' for IE11. Please let me know if you find any specific bugs for IE11 from here. :)
