### ISSUE TITLE
Can we achieve user to user private chat through babble?

### ISSUE THREAD

**Issue by AnilKadiyala** [gdpelican/babble#228]
Hi, As per our requirement, we are trying to personalise the chat between the logged in user and the selected user, by not broadcasting a messages to all the users in the group or category.

before doing that, want to check whether it is possible with babble to click on user of logged in user's choice and to have a private chat between both.

awaiting for your reply, thanks in advance.

**Comment by gdpelican** [comment]
This is now a feature of babble, simple enable the 'enable pms' option in the plugin settings panel
