### ISSUE TITLE
Blank page due to missing module

### ISSUE THREAD

**Issue by makyo** [gdpelican/babble#231]
Running into a problem with loading the page once babble is installed.

```
Error: Could not find module `discourse/lib/emoji/toolbar` imported from `discourse/plugins/babble/discourse/widgets/babble-composer`
    at o (_ember_jquery-a8dcbd3….js:59252)
    at i (_ember_jquery-a8dcbd3….js:59230)
    at n.state (_ember_jquery-a8dcbd3….js:59287)
    at e (_ember_jquery-a8dcbd3….js:59154)
    at require (_ember_jquery-a8dcbd3….js:59286)
    at _application-508e7dc….js:43379
    at Array.forEach (<anonymous>)
    at Object.n (_application-508e7dc….js:43374)
    at Object.n.initialize (_application-508e7dc….js:1282)
    at _ember_jquery-a8dcbd3….js:16430
```

Discourse version: [82ed514](https://github.com/discourse/discourse/commit/82ed51450e4b2912d3c650acd7a8332f90de9dc4)

Babble version: [7ab1286](https://github.com/gdpelican/babble/commit/7ab1286656d23a5d8170d066b3d48d8c3e827bbc)

**Comment by ivissie** [comment]
Yeah, Same issue. I had to disable babble to get the site up again.

Discourse: v1.9.0.beta4 +268

**Comment by elcojacobs** [comment]
It seems that even http://discourse-babble.com/ is affected.

I was looking to install babble, but If it even affects the demo site, how do I know that this won't happen to my instance?

**Comment by AndyatFocallocal** [comment]
same

**Comment by nguyenminhkhmt** [comment]
same here. hope you can fix it soon. thank you.

**Comment by baonq-me** [comment]
Same here.

**Comment by xpepper** [comment]
We had the same issue while updating Discourse from v1.9.0.beta2 to 1.9.0.beta6. We had to remove the babble plugin from the `app.yml` file (disabling it was not enough for us to fix the problem).

**Comment by mrgusmuller** [comment]
Disabling was enough to fix.

**Comment by SystemZ** [comment]
Any news on this @gdpelican ?
Looks like serious issue preventing me to upgrade Discourse to newest version.

**Comment by gdpelican** [comment]
This is now fixed thanks to a patch by @angusmcleod
