### ISSUE TITLE
change size images on chat (form local backup process)

### ISSUE THREAD

**Issue by userOperaFF** [gdpelican/babble#238]
May I possible add CSS fixed size images form process local backup images when anybody paste image with link?

```
/* autosize images on chat */
.babble-post-cooked img {
    max-width: 100%;
    height: auto;
}

```

| before | after |
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/33114475/32172715-d75f4452-bd7c-11e7-9415-12681c3bea93.png) | ![image](https://user-images.githubusercontent.com/33114475/32172577-641a8b3c-bd7c-11e7-8131-18ab41dcb3fd.png) |

---

Works good in full page version chat.

No breaks graphic emoticons.

**Comment by gdpelican** [comment]
Thanks for the suggestion, I've thrown this into the sidebar branch :)
