### ISSUE TITLE
Lacking responsiveness for mobile phones

### ISSUE THREAD

**Issue by JSey** [gdpelican/babble#24]
Unfortunately, I don't really have a clue on how to tackle this, but I thought I'd report it anyway: if you try to use the shoutbox from a mobile phone, you will most likely end up with the on-screen keyboard hiding the input box. Furthermore, you cannot scroll up, so you basically have to type your shout text blindly. 

Tested this on an Android device, I don't know about iOS.

**Comment by gdpelican** [comment]
Hm, I wonder if this is still an issue now that we've moved to a sidebar on mobile?

**Comment by JSey** [comment]
Currently, this just looks a bit weird (tried with an almost empty shoutbox - here, the textarea floats at the bottom until you activate the on-screen keyboard...). I will report back as soon as I have some more tests.

**Comment by gdpelican** [comment]
Be sure to update to the latest; that should like a bug from a few commits ago.

**Comment by JSey** [comment]
Oh, all right. Will do after my importer finishes (i.e. tomorrow...)

**Comment by JSey** [comment]
Works all right now.
