### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by doctsf** [gdpelican/babble#243]
Hello

![image](https://user-images.githubusercontent.com/34936824/34434329-a5569f0e-ec85-11e7-9122-8a642f7cf6c5.png)

I tried  to reproduce :
![image](https://user-images.githubusercontent.com/34936824/34434377-0df49264-ec86-11e7-8434-bac69c9252d5.png)

**Comment by gdpelican** [comment]
This should now be fixed I believe, please let me know if you see it again.
