### ISSUE TITLE
Babble Sandbox theme switch issue

### ISSUE THREAD

**Issue by Devilin-Pixy** [gdpelican/babble#248]
Was looking into this plugin for possible use and noticed the following issue on the sandbox website. Not sure if this is directly an issue with the plugin itself or just requires proper CSS styling to be setup. Just wanted to mention it regardless.

Chat in the sidebar looks fine in standard light mode/theme, but when switching to the dark mode/theme, text becomes unreadable due to the background color not changing accordingly. Likely an easy fix in class babble-sidebar (CSS). Perhaps requires looking into babble.scss background: $primary / $secondary.

**Comment by gdpelican** [comment]
These styling issues should be resolved with the PMs feature.
