### ISSUE TITLE
Babble notification icon impinging on private message notification

### ISSUE THREAD

**Issue by gdpelican** [gdpelican/babble#25]
![adc58dce9b8b1f20554df762e3b433bc0a6d582f](https://cloud.githubusercontent.com/assets/750477/9428145/b057c2e2-496d-11e5-93a3-c82e70f6e3b8.jpg)

**Comment by JSey** [comment]
How do we address this? Moving the Babble badge to the left? Since there shouldn't be anyone sitting to the left of us, that should be fine, I guess?

**Comment by JSteed** [comment]
I prefer the moving-it-to-the-left solution, personally.

**Comment by gdpelican** [comment]
Fixed with #27
