### ISSUE TITLE
Allow user to hide chat function

### ISSUE THREAD

**Issue by eugen-manjaro** [gdpelican/babble#255]
Hello!
Some users don't like chats, other do. Some would like to spend less time following new messages...
Please, allow a user to disable babble chat in user's Discourse settings!
Regards

**Comment by Yorper** [comment]
Totally agree with the above. I need an op-out feature for the sake of my sanity!

Thanks.

**Comment by gdpelican** [comment]
There is now a user-level option for this under preferences > interface.
