### ISSUE TITLE
Chat icon not showing after updating discourse

### ISSUE THREAD

**Issue by hhyyrylainen** [gdpelican/babble#259]
I upgraded discourse to version v2.1.0.beta3 +136 (535732b) and now the chat icon is no longer showing up.

I hope this isn't caused by the theme I'm using. Even when looking at the generated html I can't see any reference to the icon.

The updates page is showing that all my plugins are up to date.

**Comment by gdpelican** [comment]
Sorry for the delayed reply on this one.

Can you specify which theme you're using? We recently patched up a popular theme or two which were applying styles which made the chat button invisible.

**Comment by hhyyrylainen** [comment]
Our theme is based on Vincent but it has been modified quite a bit. So even when I switch to the default theme the button doesn't appear, perhaps due to the customized header bar. The chat button does work on mobile.

This is the site: https://community.revolutionarygamesstudio.com

**Comment by gdpelican** [comment]
I managed to fix by adding some custom css to your theme, but I've also pushed a fix that should make Babble a bit more resilient to theme modifications.

**Comment by hhyyrylainen** [comment]
I updated the plugin and the chat icon is now showing up. Thank you
