### ISSUE TITLE
Line wrap issues

### ISSUE THREAD

**Issue by JagWaugh** [gdpelican/babble#260]
at d1083fb

Line wrap works while composing, but is broken after posting, then fixes itself after a while.

![image](https://user-images.githubusercontent.com/24650566/43682817-6c83022a-987f-11e8-8a15-082c8021f63d.png)

Then a bit later:

![image](https://user-images.githubusercontent.com/24650566/43682834-aa0ffeea-987f-11e8-8685-72ec126e3aaa.png)

**Comment by gdpelican** [comment]
Alright, I've pushed a fix for this in latest, let me know if that fixes it for you?
