### ISSUE TITLE
Error creating a group chat, wont save group

### ISSUE THREAD

**Issue by bilalghalib** [gdpelican/babble#264]
I made short bug reporting video. When I try to create a new group it wont allow me to pick anything except "trust-level-0" as a group type, it will let me select it yet when I leave the page and return it will have returned it to "trust-level-0"
Hope this video clears things up. I just installed it today and pulled from git, so it should be a fresh bug.
Thanks! Hugs!
https://www.useloom.com/share/c7247ece36ac4c9bb7474a84cb33526d?focus_title=1&muted=1

**Comment by gdpelican** [comment]
Thanks for the exceptional bug reporting. I've pushed a fix to latest. Let me know if that resolves it for you?

**Comment by bilalghalib** [comment]
You are a wonderful human being. Thank you so much, I'll do a fresh git pull and let you know. Thanks!

**Comment by bilalghalib** [comment]
Just updated the plugin, it seems that there's another strange bug now. It says: 
"Unable to save that chat channel. Please try again."
here's a video showing the process 
https://www.useloom.com/share/67337a5a1e0f4fedaa78a555d08a1f6d?focus_title=1&muted=1

I'm somewhere loud so I can't share audio. Thanks for your efforts!

**Comment by gdpelican** [comment]
Alright, I've pushed up a fix which accounts for some very recent changes to Discourse core, so ensure that you're running the latest Discourse code and give it another go?

**Comment by bilalghalib** [comment]
All seems to be well. Ah, the shifting grounds of a plugin developer ;)
Thanks so much!
