### ISSUE TITLE
Mobile CSS shows chat icon when no chats are available to users.

### ISSUE THREAD

**Issue by simonv3** [gdpelican/babble#266]
We use the chat on our install for moderators to chat, and it's been working great. It doesn't show for other users on the desktop version of the site (which is great), but for mobile users it shows in the main header, but doesn't do anything when clicked on. Can this be fixed? What would need to happen to fix it? I figure we can probably fix it in our own theme, but it's probably something that should be fixed here as well?

**Comment by gdpelican** [comment]
Hi @simonv3, can you confirm that you're on the latest version of Babble? I believe I've fixed this issue in the past week, so an update should fix it.

If that's not the case, could you link me to the forum in question or, alternatively, provide me with steps to repro the issue on https://discourse-babble.com?

**Comment by simonv3** [comment]
Ah! No I don't believe we've updated in the past week. I'll get one of our admin to try that and report back. Thanks!

**Comment by gdpelican** [comment]
I believe this should now be fixed
