### ISSUE TITLE
🐛 Audio notification is not played  

### ISSUE THREAD

**Issue by azawawi** [gdpelican/babble#268]
Hi @gdpelican. Thanks for your awesome plugin. I tested on latest Chrome/Firefox on Linux and no audio notification was played. Is this still a feature?

**Comment by gdpelican** [comment]
Hi @azawawi sorry for the delayed response here.

The audio notifications have been moved to a user-specific setting under 'Interface' in your user settings, and should trigger when you get a notification or a new message in the chat you're viewing now.

![captura de pantalla 2018-11-11 a la s 3 02 45 p m](https://user-images.githubusercontent.com/750477/48308170-eef12f80-e5c2-11e8-8e85-988cee020c08.png)

**Comment by azawawi** [comment]
Thanks for pointing out the problem :+1: Anyway, is there a way we can have a global setting to simplify administration? I think nowadays users can just mute the tab on modern Firefox / Chrome.

I guess the change was done in https://github.com/gdpelican/babble/commit/eb38e941105315995c9c6c3c55935c96fd01791d.
