### ISSUE TITLE
Babble chat alert always showing 11 alerts. Even all have been read successfully.

### ISSUE THREAD

**Issue by mfarooq-seladigital** [gdpelican/babble#269]
@gdpelican  Even after successful reading of chat messages. discourse babble plugin keeps showing alert. Same issue on all browsers and even mobile app. see following screenshots for detail.
**Discourse version:** v2.2.0.beta4 +11
**Babble version:** 4.0.7

![image](https://user-images.githubusercontent.com/25738877/48112610-3f395c00-e268-11e8-9670-180034517783.png)
![image](https://user-images.githubusercontent.com/25738877/48112695-abb45b00-e268-11e8-987a-95ad99e98be5.png)

**Comment by gdpelican** [comment]
Hey @mfarooq-seladigital is this only happening for DMs, or are @mentions in the chat channels sticking for you as well?

**Comment by mfarooq-seladigital** [comment]
@gdpelican i am having both cases (DMs and @mentions) in current chat for which its showing counter 8.

**Comment by mfarooq-seladigital** [comment]
done
