### ISSUE TITLE
🐛 ⬆ key causes loss of focus on a new chat message

### ISSUE THREAD

**Issue by azawawi** [gdpelican/babble#272]
While creating a new message, pressing ⬆ causes the focus to go to the last chat message. This has been tested on the latest Firefox/Chrome browsers. This causes some data loss / confusion since you update the last message instead of creating a new one. Thanks.

**Comment by gdpelican** [comment]
Alright, I've updated this so that we only jump to the last post to edit when the current text box is empty.

**Comment by azawawi** [comment]
Thanks. :+1:
