### ISSUE TITLE
Expand button and Font Awesome 4.7/5 SVG

### ISSUE THREAD

**Issue by krystian3w** [gdpelican/babble#273]
![image](https://user-images.githubusercontent.com/35370833/50480494-85937780-09dc-11e9-96e8-071e96d88b04.png)

In dev tools I cannot see CSS contains with: `class="fa d-icon d-icon-expand svg-icon svg-node"`

```html
<button class="widget-button btn normalized no-text btn-icon" aria-label="Expand chat" title="Expand chat">
   <svg class="fa d-icon d-icon-expand svg-icon svg-node" aria-hidden="true">
      <use xlink:href="#expand"></use>
   </svg>
</button>
```

And shadow-root is empty:

![image](https://user-images.githubusercontent.com/35370833/50480822-8e854880-09de-11e9-96b8-42e45e3100ac.png) |
--- |

**Comment by gdpelican** [comment]
@pmusaraj Do you have any thoughts on this one? Seems like an svg-related icon issue.

**Comment by pmusaraj** [comment]
Yes, this is because in core we switched from using the FA 5 icon for expand to a custom SVG of the FA 4.7 icon, and there were naming changes. Fixed it in a quick one-liner PR.
