### ISSUE TITLE
Attachment feature not working

### ISSUE THREAD

**Issue by rossmith49** [gdpelican/babble#289]
The attachment feature is not working on my instance, and some others have reported this issue as well: https://meta.discourse.org/t/babble-a-chat-plugin/87297/308

I've tried on mobile, desktop browser & via discourse app, no luck. 

It will let me browse and look for the file, select and then "Open" but then nothing ever happens.

I have the version 4.1.1 of the plugin. Please let me know what other info you may need to troubleshoot.

**Comment by azawawi** [comment]
@rossmith49 Can you please check it now after https://github.com/gdpelican/babble/pull/290 has been merged?

**Comment by rossmith49** [comment]
> @rossmith49 Can you please check it now after #290 has been merged?

Can confirm that after I upgraded to latest Discourse update, then upgraded Babble, attachment feature is indeed working.

**Comment by azawawi** [comment]
Thanks for reporting this issue. Kindly close it. All work was done by @R45hk4r. Big thanks to him.
