### ISSUE TITLE
Please delete email addresses from the demo server

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [gdpelican/babble#300]
I accessed the Babble Demo server today and was a bit dismayed that I had to provide my email address just to have a look. Nonetheless, I did so.

If I've understood the add-on correctly, the add-on provides the side pop-out panel for chatting.  I liked what I saw.

However, now that I've viewed the demo, I am concerned that my email address has become a permanent addition to that database, along with lots of other people's addresses.

Can you please wipe the user list back to a seed group that is necessary to demonstrate the functionality.

**Comment by gdpelican** [comment]
You can delete your account on a Discourse instance by visiting `Preferences -> Delete account`, so long as you haven't made a certain number of posts (on that instance it's 1000, so basically anyone should be able to)

I also wipe the db for that instance occasionally (semi-yearly or so), and don't do anything with the information stored there.

**Comment by Napoleon-BlownApart** [comment]
Thanks!
