### ISSUE TITLE
Resizing the .babble-compose text area results in scroll bars instead of resizing the drop down.

### ISSUE THREAD

**Issue by djlobster** [gdpelican/babble#34]
![2015-08-26_13-50-56](https://cloud.githubusercontent.com/assets/12630047/9501630/671f1e06-4bfa-11e5-9c86-babd2955e2db.png)

https://dl.dropboxusercontent.com/u/60760072/ShareX/2015/08/2015-08-26_13-49-20.mp4

I'm not sure if the dropdown not being able to resize is intended or not, but if it is not then the text area should not be able to be resized either. Maybe only allow vertical resizing for the dropdown and text area?

**Comment by gdpelican** [comment]
Ah yeah, we should just disallow resizing the text area; should be a simple fix.

**Comment by JSey** [comment]
Yup. Shall I push you the fix? Was just testing it...

**Comment by gdpelican** [comment]
Yes, you rock!

**Comment by JSey** [comment]
Thx. Right back at you… :)

**Comment by gdpelican** [comment]
Should be fixed with #36
