### ISSUE TITLE
Sound notification option

### ISSUE THREAD

**Issue by MiguelAngelLV** [gdpelican/babble#35]
Would be posible add a "sound" to notification new messages? With mute option of course.

**Comment by gdpelican** [comment]
Seems like it'd be possible, yes.

**Comment by gdpelican** [comment]
Upon investigating this further, I don't think this will go into the plugin anytime soon... I don't think that Discourse itself supports playing sounds anywhere else, and I'd rather not add that as a dependency to just this plugin.

One thing that I am interested in doing at some point is changing the navbar title to indicate that there's a new chat message... although that may not happen for a while and may conflict with Discourse's existing 'new topics' notification (`(1) Discourse`)
