### ISSUE TITLE
Ctrl+Enter not working in Firefox

### ISSUE THREAD

**Issue by JSey** [gdpelican/babble#38]
First: great work on the 0.4.0 release! 

Minor nitpicking: the Ctrl+Enter functionality (which is great, btw - and my team has just yesterday started to complain that you cannot insert line breaks but for <br>s) does not work for Firefox. This is simply due to the fact that Firefox does not convert Ctrl+Enter or Alt+Enter into line breaks when handling input (unlike Safari or Chrome).

I will send a PR for a very basic fix: allow Ctrl, Alt and Shift as modifiers to let a keycode 13 pass through. The great thing about that would be: it allows users to stick to the habits of their favourite browsers.

**Comment by gdpelican** [comment]
Closed with #39
