### ISSUE TITLE
Image scaling with correct aspect ratio?

### ISSUE THREAD

**Issue by JSteed** [gdpelican/babble#40]
Tried pasting an image for the first time yesterday. I like that the width is scaled, but it doesn't seem to scale the height accordingly? In short: the aspect ratio looks way off to me:

![screenshot-chanologynorge org 2015-08-28 08-06-15](https://cloud.githubusercontent.com/assets/13939381/9540229/82f5eaf2-4d5c-11e5-9656-e1b7a4a3ab2d.png)

A horizontal slider/scroller also cropped up after pasting the image.

**Comment by JSey** [comment]
Oops. Could you share your browsers Make&model (since I cannot yet repro this)? Thanks. I have a suspicion for an easy fix, but would like to test that first.

**Comment by JSteed** [comment]
I've tried it in Opera 32.0.1948.4 (beta), Chrome 44.0.2403.157 m (64-bit) and Firefox 40.0.3. The same happens in all three.

**Comment by JSey** [comment]
This is totally odd. I cannot reproduce this with any of your browsers. How did you embedd the image? Did you enter an ordinary <img tag? Did you specify width+height?

**Comment by JSteed** [comment]
Doh. To be honest, I just pasted the URL straight in, with no html tags. The URL had some parameters appended, so I thought those messed it up when it didn't show. I just removed them in the chat thread itself. Then it worked, but with the wrong aspect ratio.

Tried using HTML tags now. Works fine. Sorry about the confusion.

**Comment by JSey** [comment]
Ok, good. Could you paste me the URL including the attributes and parameters? I'd like to try if I can override them so that does not happen too often.

**Comment by JSteed** [comment]
No idea what they were, I'm afraid. Just the typical social media tracking stuff, I guess. But a plain Imgur URL doesn't work either; it just shows up as a link here.

**Comment by JSey** [comment]
Hm... was it something like
```<blockquote class="imgur-embed-pub" lang="en" data-id="eFyGazv"><a href="//imgur.com/eFyGazv">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>```
or something easier like
```<img src="http://i.imgur.com/9ve6Bj0.jpg" style="width: 634px; height: 960px;" alt="baa" />```
?

**Comment by JSey** [comment]
Uh, never mind. The second alternative works already, the first one is beyond anything we should care about IMHO…

**Comment by JSteed** [comment]
I didn't specify the size in my HTML-tag. It was simply:

`<img src="http://i.imgur.com/KqeOQUZ.jpg">`

**Comment by JSey** [comment]
Currently, you have to paste HTML in order to post an image in the chat. I personally would not offer an easy way to post images, they're not really chat material in my opinion.

You're totally right about the scrollbars - I will subtract 10px in order to get rid of that.

**Comment by JSteed** [comment]
Good point. I doubt I'll post images myself. I was just trying to figure out what was possible/not possible with Babble.

And thanks for fixing the scrollbars! Really appreciate what you guys are doing.

And again, sorry for the confusion earlier.

**Comment by JSey** [comment]
Nothing to be sorry about. Thanks for the feedback and test driving Babble - the main kudos go to @gdpelican for the great plugin - I'm just ironing out some tiny wrinkles here… ;)

**Comment by JSteed** [comment]
My pleasure!

@gdpelican:

![john_steed__185410](https://cloud.githubusercontent.com/assets/13939381/9558493/a1f05732-4de6-11e5-9129-4a51cf676206.jpg)

(Babble doesn't work at all in the latest beta, btw: 
![screenshot-chanologynorge org 2015-08-29 00-33-31](https://cloud.githubusercontent.com/assets/13939381/9558498/b35dd760-4de6-11e5-8394-ca2ebc032bd1.jpg)

Chat window doesn't open, and I get this spinning loading-thing on top of the nav bar - in all browsers.)

**Comment by gdpelican** [comment]
I'll take a peek and get this sorted over the weekend.

On Friday, August 28, 2015, JSteed <notifications@github.com> wrote:
> My pleasure!
>
> @gdpelican:
>
> <
https://ci4.googleusercontent.com/proxy/IMgE0MJeNqwnswVRV78QY4Oeei6WilBd3_BPsSs-wlxay9yjbSU3hVUpZ_N57rXJF1hiv8HQKpblY77IBWZ0QAnwQlWJX8ho4VDL8vBBQqCu9-mGpxIot_26_QZ_5NSatbd15iT8ijI2ezKmOyzmbpP_1rOQsRuPGmc=s0-d-e1-ft#https://cloud.githubusercontent.com/assets/13939381/9558493/a1f05732-4de6-11e5-9129-4a51cf676206.jpg
>
>
> (Babble doesn't work at all in the latest beta, btw:
> <
https://ci4.googleusercontent.com/proxy/Hr75XTHThjHRZK7j9GGGwVI1LtoATbyN85B2L8pRzkRBk0bHVh1TWEQnAfGMaR_S3TD57Xlx-1cmRM3xkZDGOR9mY7tDCozkp1HgovH1J5wlm_V4hmhJhYKex4qD7zmBuFtrJ-qfL6nF-Co5g4p0OyFqxGO5S9z-t74=s0-d-e1-ft#https://cloud.githubusercontent.com/assets/13939381/9558498/b35dd760-4de6-11e5-8394-ca2ebc032bd1.jpg
>
>
> Chat window doesn't open, and I get this spinning loading-thing on top of
the nav bar - in all browsers.)
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/4CwF44uF314O8IfqdQV231kkLNE5Kcy4c1mTagxEPV4lwEn5Hcb4hlyh9cs2cEjNZ99y9jzNVZVWAwVsfbXEXP8-xZVQPXBj8Mqw7KlV6VrLRuVuZHuFz8ksnHFgFgBOp8yQjnlEZCBgkGcnzzk-YVGpW2ZOPw=s0-d-e1-ft#https://github.com/notifications/beacon/AAtzjWmwGB4TwbdZ3vdHd_kvIQLS7SYDks5osNuegaJpZM4Fz2Wf.gif
>

**Comment by gdpelican** [comment]
Is this still an issue @JSteed ?
