### ISSUE TITLE
Babble displaces system notification badges in fix-this-thing?!

### ISSUE THREAD

**Issue by JSey** [gdpelican/babble#43]
I just gave the fix-this-thing branch a spin on the latest Discourse - with very odd results. Before Babble is active, everything's fine. After installing, the system notification looks like this:
![bildschirmfoto 2015-09-02 um 19 54 07](https://cloud.githubusercontent.com/assets/9109505/9639492/95d54e66-51ac-11e5-939a-d8f85756a2fe.png)
...because there's a ```.d-header .icons .unread-private-messages``` style definition with a ridiculous ```left:82px;``` - I don't have any clue where this might come from. Just wanted to post my findings… :(

**Comment by gdpelican** [comment]
Huh weird. At least locally for me, notifications are still broken,
although maybe it's just that the icon is off in a weird place.

Anyway, yeah, still a complete WIP, but thanks for the feedback. :)

**Comment by MiguelAngelLV** [comment]
Hi. I install the WIP version, all ok except the notifications are still broken and scroll to last message when open the chat.

**Comment by JSey** [comment]
Mothership's issue: https://meta.discourse.org/t/feedback-on-new-hamburger-and-user-menus/32519/203?u=jsey
