### ISSUE TITLE
Height in mobile version

### ISSUE THREAD

**Issue by MiguelAngelLV** [gdpelican/babble#46]
The height in mobile is not correct.

The textarea is over the last mensaje.

![screenshot](https://cloud.githubusercontent.com/assets/638110/9692343/b94351e8-5348-11e5-9177-d789adc120ee.png)

**Comment by gdpelican** [comment]
Hmm, thanks for the catch @MiguelAngelLV; I've just pushed a fix for it in the latest, would you mind rebuilding and seeing if this is still an issue for you? It looks ok on my browser phone emulators, but I don't have a phone to test with at the moment.

**Comment by MiguelAngelLV** [comment]
It works fine now.
