### ISSUE TITLE
Minor glitch on older Firefoxes

### ISSUE THREAD

**Issue by JSey** [gdpelican/babble#54]
Here's how Babble looks like in Firefox ESR 17 (I know… but Discourse has a minimum spec of FF 14):

![bildschirmfoto 2015-09-12 um 18 53 30](https://cloud.githubusercontent.com/assets/9109505/9832833/b36923aa-5984-11e5-930c-b2056beecf28.png)

(Happens only when the browser window is relatively small and spans the whole browser height…)

**Comment by gdpelican** [comment]
Duly noted, although I might have a tough time convincing myself to fix this :) Thanks for reporting though; if I get a few complaints in this direction I'll take a look at it.

**Comment by gdpelican** [comment]
Going to close this as wontfix :monkey_face:
