### ISSUE TITLE
Number in notifications

### ISSUE THREAD

**Issue by JSey** [gdpelican/babble#57]
After a massive chat session yesterday, one of my team colleagues (who missed the session) mentioned that the notification stated a very high number of unread chat messages - but the number of messages visible in Babble was much lower. We should introduce a max() here…

**Comment by JSey** [comment]
Is it safe to assume that there are at max ```babble_max_topic_size``` unread posts waiting? Or is some client side script limiting the amount of shouts getting pulled from the server?

If that's safe, I can propose a smallish fix for this…

**Comment by gdpelican** [comment]
I've put in a fix for this here, which makes it so the maximum number of notifications you see is equal to the number of posts in the postStream (20 by default), with a '+' if there's more notifications than that serverside.

Someday, once someone complains about it, I'll go back in and allow for a loading of chat history... surprisingly though, no one's complained yet. :dancer:
