### ISSUE TITLE
Timestamps <1min cause word breaks

### ISSUE THREAD

**Issue by JSey** [gdpelican/babble#66]
Some are bad, others not so much. Here's Firefox (worst, <1mi<br />n is just ugly), Safari and Chrome (Opera looks alike):
![bildschirmfoto 2015-09-20 um 22 17 43](https://cloud.githubusercontent.com/assets/9109505/9982780/2e542098-5fe7-11e5-80da-2e263abaac8d.png)
![bildschirmfoto 2015-09-20 um 22 28 13](https://cloud.githubusercontent.com/assets/9109505/9982779/2e537da0-5fe7-11e5-9f8a-c92c12a06882.png)
![bildschirmfoto 2015-09-20 um 22 17 32](https://cloud.githubusercontent.com/assets/9109505/9982778/2e4b92f2-5fe7-11e5-87f8-a14bda9dea67.png)

**Comment by gdpelican** [comment]
There's been an update which has changed the format from '<1min' to '<1m', which I think has this resolved; are you still seeing this @JSey
