### ISSUE TITLE
Chat topic creation for special groups currently undocumented

### ISSUE THREAD

**Issue by JSey** [gdpelican/babble#67]
First of all, congratulations for this release - this is great stuff!

I have found one inconsistency: if a user has insufficient rights to read a chat topic, they should not get the topic switcher or the topic name in the list of chat topics. They cannot click into that chat, however, but they should not see that list in the first place.

**Comment by gdpelican** [comment]
Hm, I'm not seeing that behaviour; can you describe the steps you went through?

**Comment by JSey** [comment]
Maybe I did something stupid:

* Updated to 0.7.1
* created another chat topic in the rails console
* moved that chat topic into our staff category where non-staff members do not have any access rights 
* tried it: staff can post+read in both topics using the switcher
* non-staff can click the switcher, but cannot enter the team chat topic

**Comment by gdpelican** [comment]
Ahah! That is _not_ the intended use case, which is currently undocumented,
heh. (I was going to take some time to smoke test it tap up some docs
before announcing it on the meta thread, but you're an early adopter. :)

When you create the babble topic, try passing a group to it, like so:

```
Babble::Topic.create_topic "Staff only chat", Group.find_by(name: "staff")
```

This group defaults to Trust Level 0 (the 'everyone' group is a little
weird, so trust level 0 is basically 'if you're logged in, you can see
it'), but can accept any group in your db.

**Comment by JSey** [comment]
:+1: thx. Will try and report back.

**Comment by JSey** [comment]
Works. Changed issue title to reflect the "real problem" (if you don't want to blame this issue on ISO layer 8...) ;)

**Comment by gdpelican** [comment]
Now that's a thing I can fix. After :zzz:.

**Comment by JSey** [comment]
Do that! :smile:
