### ISSUE TITLE
Babble broken since Discourse v1.5.0.beta4

### ISSUE THREAD

**Issue by tedstrauss** [gdpelican/babble#87]
the menu icon is missing, so zero functionality.
https://meta.discourse.org/t/babble-a-chat-plugin/31753/127

**Comment by gdpelican** [comment]
This has since been fixed; have you updated to the latest?
discourse-babble.com is running the latest Discourse / Babble together, and
appears to work alright.

**Comment by tedstrauss** [comment]
Ya my babble plugin is updated to the latest.
My discourse is also up to date. in tghe dashboard is says no upgrade needed. On the /admin/upgrade page it says there are 53 new commits on discourse.

Does the container need to be rebuilt?

**Comment by gdpelican** [comment]
Try running the following commands in your Rails console:

```
category = Category.find_by(name: 'chat')
category.topics.update_all(user_id: Babble::User.instance.id)
```

**Comment by tedstrauss** [comment]
still not working. 
rebuilt the container, and no change.
is there a log file where i should look for info?

**Comment by tedstrauss** [comment]
i recreated the chat category and the babble topic. 
when viewing the chat category the topic shows "-1" in the replies column
when i click to open the topic the page loads mostly blank (only discourse header and wrench icon appear)

**Comment by tedstrauss** [comment]
this issue is now resolved
