### ISSUE TITLE
Title overlaps text on mobile

### ISSUE THREAD

**Issue by kymetro9999** [gdpelican/babble#93]
Something's up with the CSS on the chat channel title. Desktop is not affected, only mobile. It's positioned lower than it should be and overlaps with the text area. When scrolling this frequently means overlapped text.

I don't think its a text overflow problem. Even short channel names such as "chat" are affected.

See screenshot:
![screenshot_2015-12-02-12-37-22](https://cloud.githubusercontent.com/assets/11318280/11551557/3b8137de-9948-11e5-8cb3-8629ff9c5742.png)

**Comment by gdpelican** [comment]
cc @JSey any idea about this one? I can confirm it... wonder if there's a better way to think about styling this sidebar, which has, to this point, has been really fragile.

**Comment by gdpelican** [comment]
This one should be fixed with the markup refactor
