### ISSUE TITLE
Not working in new beta v1.5.0.beta7 +3

### ISSUE THREAD

**Issue by thisgeekza** [gdpelican/babble#97]
I've just updated my site (via full rebuild) to v1.5.0.beta7 +3 and now the babble icon is no longer visible. The plugin is enabled and working in so far as settings are concerned, but there is no interface for it now.

**Comment by gdpelican** [comment]
Hm. I just upgraded discourse-babble.com to the latest, and am not experiencing this.

Do you have other plugins installed? Are you seeing errors in the javascript console? Are there network requests failing under the 'network' tab?

**Comment by thisgeekza** [comment]
Gah, I rebuilt without the other plugins and it's now working. I guess suddenly one of the plugins is conflicting. I'll try figure out which one.

**Comment by thisgeekza** [comment]
It's caused by discourse-alert.

**Comment by gdpelican** [comment]
That plugin's really small (25 lines of code or so); I can't imagine it's conflicting with Babble directly.

If I had to guess, I'd guess that it needs to updated to comply with the new compatibility layer changes outlined here: https://meta.discourse.org/t/deprecating-es6-compatibility-layer/35821

I reckon pinging @zogstrip on meta and he'll patch it up right quickly.
